version: '3.8'

services:
  # === Orchestrator ===
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DATA_PATH}/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.1'
    
  # === Music Streaming Server ===
#  navidrome:
#    image: deluan/navidrome:latest
#    container_name: navidrome
#    restart: unless-stopped
#    ports:
#      - "4533:4533"
#    volumes:
#      - ${DATA_PATH}/navidrome:/data
#      - ${STORAGE_PATH}/media/music:/music:ro
#    networks:
#      - homelab
  
  # === Media Server ===
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ${DATA_PATH}/jellyfin/config:/config
      - ${DATA_PATH}/jellyfin/cache:/cache
      - ${STORAGE_PATH}/media/movies:/media/movies:ro
      - ${STORAGE_PATH}/media/series:/media/series:ro
      - ${STORAGE_PATH}/media/music:/media/music:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # === TV Series Management ===
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ${DATA_PATH}/sonarr:/config
      - ${STORAGE_PATH}/media/series:/series
      - ${STORAGE_PATH}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

  # === Movie Management ===
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ${DATA_PATH}/radarr:/config
      - ${STORAGE_PATH}/media/movies:/movies
      - ${STORAGE_PATH}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
  
  # === Music Management ===
#  lidarr:
#    image: linuxserver/lidarr:latest
#    container_name: lidarr
#    restart: unless-stopped
#    ports:
#      - "8686:8686"
#    volumes:
#      - ${DATA_PATH}/lidarr:/config
#      - ${STORAGE_PATH}/media/music:/music
#      - ${STORAGE_PATH}/downloads:/downloads
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    dns:
#      - ${EXTERNAL_DNS}
#    networks:
#      - homelab

  # === Indexer Management ===
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ${DATA_PATH}/prowlarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  homelab:
    name: homelab
    driver: bridge