version: '3.8'

services:
  # === Docker Manager ===
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - homelab
  # === NETWORK STACK ===
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    dns:
      - 8.8.8.8      # Google DNS primaire
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - homelab
  # === METRIC STACK ===
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "65534:65534"
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - homelab

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafana/dashboard-configs:/etc/grafana/provisioning/dashboards
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - homelab

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - homelab

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - homelab
  # === MEDIA STACK ===
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - ./storage/media/movies:/media/movies:ro
      - ./storage/media/series:/media/series:ro
      - ./storage/media/music:/media/music:ro
    networks:
      - homelab

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    dns:
      - 8.8.8.8      # Google DNS primaire
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./data/sonarr:/config
      - ./storage/media/series:/series
      - ./storage/downloads:/downloads
    environment:
      - PUID=911
      - PGID=911
    networks:
      - homelab

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    dns:
      - 8.8.8.8      # Google DNS primaire
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./data/radarr:/config
      - ./storage/media/movies:/movies
      - ./storage/downloads:/downloads
    environment:
      - PUID=911
      - PGID=911
    networks:
      - homelab

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    dns:
      - 8.8.8.8      # Google DNS primaire
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ./data/prowlarr:/config
    environment:
      - PUID=911
      - PGID=911
    networks:
      - homelab

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    dns:
      - 8.8.8.8      # Google DNS primaire
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./data/qbittorrent:/config
      - ./storage/downloads:/downloads
    environment:
      - WEBUI_PORT=8082
      - PUID=911
      - PGID=911
    networks:
      - homelab

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    dns:
      - 8.8.8.8      # Google DNS primaire
    restart: unless-stopped
    ports:
      - "6789:6789"
    volumes:
      - ./data/nzbget:/config
      - ./storage/downloads:/downloads
    environment:
      - PUID=911
      - PGID=911
    networks:
      - homelab
      
networks:
  homelab:
    driver: bridge
