version: '3.8'

services:
  # === VPN Client ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"  # qBittorrent WebUI
      - "6881:6881"                     # qBittorrent BitTorrent port
      - "6881:6881/udp"
    volumes:
      - ${DATA_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${PROTON_COUNTRIES}
      - OPENVPN_CIPHERS=AES-256-GCM
      - BLOCK_MALICIOUS=off
      - UPDATER_PERIOD=24h
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8082/api/v2/app/setPreferences 2>&1'
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab

  # === BitTorrent Client ===
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - ${DATA_PATH}/qbittorrent:/config
      - ${STORAGE_PATH}/downloads:/downloads
    environment:
      - WEBUI_PORT=${WEBUI_PORT}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # === Usenet Client ===
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    ports:
      - "6789:6789"
    volumes:
      - ${DATA_PATH}/nzbget:/config
      - ${STORAGE_PATH}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    driver: bridge