version: '3.8'

services:
  # === VPN Client ===
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"  # qBittorrent WebUI
      - "6881:6881"                    # qBittorrent BitTorrent port
      - "6881:6881/udp"
    volumes:
      - ${DATA_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_VERSION=2.5
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${PROTON_COUNTRIES}
      - BLOCK_MALICIOUS=off
      - UPDATER_PERIOD=24h
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'sleep 10 && wget -O- --retry-connrefused --tries=10 --waitretry=5 --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - homelab
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 32M
          cpus: '0.05'

  # === BitTorrent Client ===
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - ${DATA_PATH}/qbittorrent:/config
      - ${STORAGE_PATH}/downloads:/downloads
    environment:
      - WEBUI_PORT=${WEBUI_PORT}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'

  # === Usenet Client ===
#  nzbget:
#    image: linuxserver/nzbget:latest
#    container_name: nzbget
#    restart: unless-stopped
#    ports:
#      - "6789:6789"
#    volumes:
#      - ${DATA_PATH}/nzbget:/config
#      - ${STORAGE_PATH}/downloads:/downloads
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    dns:
#      - ${EXTERNAL_DNS}
#    networks:
#      - homelab

networks:
  homelab:
    name: homelab
    driver: bridge