version: '3.8'

services:
  # === Services Dashboard ===
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # docker integration
      - ${DATA_PATH}/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - '7575:7575'
    networks:
      - homelab
    
  # === Docker Manager ===
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/portainer:/data
    networks:
      - homelab

  # === Reverse Proxy ===
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DATA_PATH}/nginx-proxy-manager:/data
      - ${CONFIG_PATH}/nginx-proxy-manager:/etc/letsencrypt
    networks:
      - homelab
    
  # === Container's Update Watchtower ===
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true  # Remove last image version
    
  # === Backup Service ===
#  duplicati:
#    image: linuxserver/duplicati:latest
#    container_name: duplicati
#    restart: unless-stopped
#    ports:
#      - "8200:8200"
#    volumes:
#      - ${DATA_PATH}/duplicati:/config
#      - ${STORAGE_PATH}:/source/storage:ro
#      - ${DATA_PATH}:/source/data:ro
#      - ./backups:/backups 
#    environment:
#      SETTINGS_ENCRYPTION_KEY: ${DUPLICATI_ENCRYPTION_KEY}
#      DUPLICATI__WEBSERVICE_PASSWORD: ${DUPLICATI_WEBSERVICE_PASSWORD}
#    networks:
#      - homelab

  # === CloudFlare Solver ===
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    dns:
      - ${EXTERNAL_DNS}
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    driver: bridge